### ISSUE TITLE
Improve installation instructions

### ISSUE THREAD

**Issue by JamieJQuinn** [UCL/pyCascadia#28]
@Devaraj-G tried installing dependencies through pipenv and came up against an error:

```
pipenv install
Creating a virtualenv for this project...
Pipfile: /home/devaraj/Desktop/Work/Results/pyCascadia-main/Pipfile
Using /usr/bin/python3.9 (3.9.4) to create virtualenv...
⠹ Creating virtual environment...RuntimeError: failed to query /usr/bin/python3.9 with code 1 err: 'Traceback (most recent call last):\n  File "/home/devaraj/.local/lib/python2.7/site-packages/virtualenv/discovery/py_info.py", line 16, in <module>\n    from distutils import dist\nImportError: cannot import name \'dist\' from \'distutils\' (/usr/lib/python3.9/distutils/__init__.py)\n'
```

Running without pipenv also fails:
```
 python3 close_boundary.py --input gdal_translate_OK08.nc --output gdal_contour_OK08.shp

and it gives an error:
Loading gdal_translate_OK08.nc
Resolution: (1251, 924)
Traceback (most recent call last):
  File "close_boundary.py", line 38, in <module>
    main()
  File "close_boundary.py", line 30, in main
    replace_land_with_zeros(input_grid[0,:])
TypeError: tuple indices must be integers or slices, not tuple
```

There is a need for more comprehensive installation instructions detailing
- Installing the correct version of python + distutils
- Installing pipenv
- Installing dependencies through pipenv
- Running scripts with pipenv

**Comment by alessandrofelder** [comment]
Moved the latter problem to separate issue #35 .
