### ISSUE TITLE
base grid in tif format gives type int16 error

### ISSUE THREAD

**Issue by Devaraj-G** [UCL/pyCascadia#58]
Running the below command:
`remove-restore  --base ../Data_Code/IAAC2/2021_07_05_gebco_2020/gebco_2020_n60.0_s37.0_w-140.0_e-119.0.tif  --output ../Data_Code/IAAC2/temp/merged_dem.nc  --spacing 0.000280000  --region_of_interest -137.250000000 -121.250000000   39.750000000   56.250000000   ../Data_Code/IAAC2/2021_07_05_noaa_Strait_of_Juan_de_Fuca_1_by_3_arcsecond/strait_of_juan_de_fuca_13_navd88_2015.nc`

gives:
_Loading ../Data_Code/IAAC2/2021_07_05_gebco_2020/gebco_2020_n60.0_s37.0_w-140.0_e-119.0.tif
Resolution: (5040, 5520)
CRS: +init=epsg:4326
Input region: [-139.99791666666667, -119.00208333333333, 37.00208333333333, 59.99791666666667]
Input spacing: 0.004166666666662877
Traceback (most recent call last):
  File "/home/devaraj/anaconda3/envs/cascadia/bin/remove-restore", line 8, in <module>
    sys.exit(main())
  File "/home/devaraj/anaconda3/envs/cascadia/lib/python3.9/site-packages/pycascadia/remove_restore.py", line 114, in main
    base_grid = load_base_grid(base_fname, region=args.region_of_interest, spacing=args.spacing)
  File "/home/devaraj/anaconda3/envs/cascadia/lib/python3.9/site-packages/pycascadia/remove_restore.py", line 77, in load_base_grid
    base_grid.crop(region)
  File "/home/devaraj/anaconda3/envs/cascadia/lib/python3.9/site-packages/pycascadia/grid.py", line 27, in crop
    self.grid = grdcut(self.grid, region=region)
  File "/home/devaraj/anaconda3/envs/cascadia/lib/python3.9/site-packages/pygmt/helpers/decorators.py", line 288, in new_module
    return module_func(*args, **kwargs)
  File "/home/devaraj/anaconda3/envs/cascadia/lib/python3.9/site-packages/pygmt/helpers/decorators.py", line 432, in new_module
    return module_func(*args, **kwargs)
  File "/home/devaraj/anaconda3/envs/cascadia/lib/python3.9/site-packages/pygmt/src/grdcut.py", line 94, in grdcut
    with file_context as infile:
  File "/home/devaraj/anaconda3/envs/cascadia/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/home/devaraj/anaconda3/envs/cascadia/lib/python3.9/site-packages/pygmt/clib/session.py", line 1358, in virtualfile_from_grid
    self.put_matrix(gmt_grid, matrix)
  File "/home/devaraj/anaconda3/envs/cascadia/lib/python3.9/site-packages/pygmt/clib/session.py", line 908, in put_matrix
    raise GMTCLibError("Failed to put matrix of type {}.".format(matrix.dtype))
pygmt.exceptions.GMTCLibError: Failed to put matrix of type int16._

**Comment by Devaraj-G** [comment]
Works ok with an .nc file, although that also has data in int16 type.

**Comment by JamieJQuinn** [comment]
This has been fixed. Closing.
